### ISSUE TITLE
Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by andrew-luhring** [babel/karma-babel-preprocessor#10]
All of my files are getting this error when karma runs chrome:

Uncaught ReferenceError: exports is not defined
base.es5.js:3 Uncaught ReferenceError: exports is not defined

## input file (base.js):

```js

import {apps} from '/js/init/apps_init.js';
import {HeaderController} from '/js/base/controllers/header.js';

export var base = apps.base().
  controller('HeaderController', HeaderController);

```

## output (base.es5.js):
```js

'use strict';

Object.defineProperty(exports, '__esModule', {
  value: true
});

var _apps = require('/js/init/apps_init.js');

var _HeaderController = require('/js/base/controllers/header.js');

var base = _apps.apps.base().controller('HeaderController', _HeaderController.HeaderController);
exports.base = base;
//# sourceMappingURL=blah

```

## karma.conf.js
```js
{
  basePath: '../',
  frameworks: ['jasmine'],

  preprocessors: {
    'public/js/**/*.js' : ['babel'],
    'tests/unit/**/*.js' : ['babel']

  },

  "babelPreprocessor": {
    options: {
      sourceMap: "inline"
    },
    filename: function(file) {
      return file.originalPath.replace(/\.js$/, ".es5.js");
    },
    sourceFileName: function(file) {
      return file.originalPath;
    }
  },

  files: [ 'public/lib/angular/angular.js',
  'public/lib/lodash/dist/lodash.compat.js',
  'public/lib/jquery/dist/jquery.js',
  'public/lib/angular-ui-router/release/angular-ui-router.js',
  'public/js/**/*.js',
  'tests/unit/**/*.js'],
  exclude: [
  ],
  port: 9876,
  colors: true,
  autoWatch: true
};

```

**Comment by shuhei** [comment]
It's because browsers don't support CommonJS, require and exports. This
plugin only transpiles file by file and does nothing to module.

How do you resolve modules outside of testing?

**Comment by andrew-luhring** [comment]
Using traceur. 
Doesn't babel understand modules? http://babeljs.io/docs/usage/modules/
I decided to try babel because the karma-traceur-precompiler plugin fails with traceur runtime errors... that oddly do not happen when I'm not using karma.

My app works fine when loaded normally in a browser with the traceur.

**Comment by shuhei** [comment]
If you use browserify and babelify, I recommend you to use karma-browserify and babelify.

**Comment by shuhei** [comment]
No, babel just transpiles ES6 module imports and exports into another
module syntax. It doesn't resolve dependencies or concat files.

**Comment by andrew-luhring** [comment]
Bummer.
Thanks

**Comment by arikkfir** [comment]
@shuhei  - may I ask how to configure the "browser.js" of Babel to transpile ES6 module imports/exports into the "ignore" module syntax?

**Comment by ambodi** [comment]
@shuhei doesn't it make sense to offer possibilities that babel will take care of that? 
>Babel is a compiler for writing next generation JavaScript.

This doesn't look like saying 

>Babel is a compiler for transpiling the next generation JavaScript.

**Comment by shuhei** [comment]
For questions/discussions about babel itself, I recommend [Slack Community](
https://babel-slack.herokuapp.com) or [Stackoverflow](
http://stackoverflow.com/questions/tagged/babeljs).

**Comment by RubyLouvre** [comment]
这百度一下就有相关的CDN了

http://www.bootcdn.cn/es6-promise/

```
<script src="//cdn.bootcss.com/es6-promise/4.0.5/es6-promise.js"></script>
<script src="avalon.js" ></script>
```
