### ISSUE TITLE
WARN [preprocess]: Can not load "babel", it is not registered!

### ISSUE THREAD

**Issue by UberMouse** [babel/karma-babel-preprocessor#12]
I'm having issues getting babel setup with Karma. I've installed the plugin with 
```npm install --save-dev karma-babel-preprocessor```
and included it in the plugins array in my karma config, annotated the paths for the preprocessor as so

    preprocessors: {
      'src/**/*.js': ['babel'],
      'test/**/*.js': ['babel']
    },

But I can't get karma to detect the loaded babel plugin for the preprocessor. Is there something I am missing?

My full karma config and package.json https://gist.github.com/UberMouse/4037d82e054b6c6eb2a8

**Comment by shuhei** [comment]
I can't find `karma-mocha` and `karma-chrome-launcher` in your `package.json`. It might be related to this issue.

**Comment by shuhei** [comment]
Also, your karma config file is named `karma.config.js` but it should be `karma.conf.js` to make karma load it automatically.

**Comment by shuhei** [comment]
Closing due to no response.
