### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by gotofritz** [babel/karma-babel-preprocessor#17]
Hi. Am I right in thinking that karma-babel-preprocessor is only one piece of the puzzle, and to unit tests ES6 with babel + karma something else is needed? But what, and why is it not documented?

Config file:

    module.exports = function(config) {
      config.set({
        autoWatch: true,
        browsers: ["Chrome"],
        client: {
          captureConsole: true,
        },
        files: [
          {pattern: "./**/templates.js", watched: true, included: true, served: true}
        ],
        preprocessors: {
          "./**/*.js": ["babel"]
        },
        "babelPreprocessor": {
        }
      });
    };

TEmplates js

    import Handlebars from "handlebars/runtime";
    // .... handlebars stuff

So it looks like karma-babel-preprocessor converts the code to ES5... then what? What is the next step? Thanks.

**Comment by adam-beck** [comment]
I'm getting this same error. I have an `import` in one of me files and that's where it is breaking. Have you found a solution for this?

**Comment by shuhei** [comment]
babel converts ES6 modules' `import`/`export` to CommonJS's `require`/`module.exports`. You still need to resolve `require`/`module.exports`.

If you want to use ES6/CommonJS modules, I recommend to use browserify + [babelify](https://github.com/babel/babelify) or webpack + [babel-loader](https://github.com/babel/babel-loader).

**Comment by shuhei** [comment]
Updated README as @gotofritz suggested. Thanks!

**Comment by kn9ts** [comment]
Here's a great blog post I found on how to use __gulp, browserify and babelify__ transform plugin for browserify.

LINK: [Using Babel and Browserify with gulp](http://problematic.io/2015/02/26/using-babel-and-browserify-with-gulp/)

**Comment by mityukov** [comment]
Is there a way to use CDN babel and still have an option to use import/export? What scripts (except of babel) should the page fetch?

**Comment by shuhei** [comment]
@mityukov Here is not a place for general babel questions. Please ask it at stackoverflow or babel slack.
