### ISSUE TITLE
ERROR [preprocessor.babel]:  Unexpected token

### ISSUE THREAD

**Issue by telekosmos** [babel/karma-babel-preprocessor#21]
Hi
I just came across this error when trying to do an object destructuring assignment with rest operator in my code, such that `let {one, ...rest} = {one: 1, two: 2, thr: 3, four: 4};`. This is working in babel in this [little demo](https://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=false&playground=false&code=let%20obj%20%3D%20%7Bone%3A%201%2C%20two%3A%202%2C%20thr%3A%203%7D%3B%0Alet%20%7Bone%2C%20...rest%7D%20%3D%20%7Bone%3A%201%2C%20two%3A%202%2C%20thr%3A%203%2C%20four%3A%204%7D%3B%0A%0Aconsole.log(rest)%3B) despite to be experimental (yet) as it is supposed to be expected for ES7 specification.

I updated the preprocessor and used the _es2015_ babel preset as recommended, but still getting the error. 

Cheers!!

**Comment by shuhei** [comment]
ES7 features are not included in the es2015 preset. ES2015 was called as ES6. Add this plugin in addition to the preset.

https://www.npmjs.com/package/babel-plugin-transform-object-rest-spread
