### ISSUE TITLE
transform-es2015-modules-systemjs won't work with karma

### ISSUE THREAD

**Issue by gajewsk2** [babel/karma-babel-preprocessor#24]
I get 
`'Unhandled promise rejection', Error{message: 'Module http://localhost:9877/src/hello.es6.js interpreted as global module format, but called System.register.`

```
    babelPreprocessor: {
      options: {
        "plugins": [
          "transform-es2015-modules-systemjs"
        ],
        "presets": [
          "es2015"
        ],
        sourceMap: 'inline'
      },
      sourceFileName: function (file) {
        return file.originalPath;
      }
    },
```

Any ideas how to address it?

Using this: https://github.com/gunnarlium/babel-jspm-karma-jasmine-istanbul

**Comment by shuhei** [comment]
Not sure at this time. Let's see answer from the repo's author.

https://github.com/gunnarlium/babel-jspm-karma-jasmine-istanbul/issues/13

**Comment by shuhei** [comment]
Closing because it seems like an issue of https://github.com/gunnarlium/babel-jspm-karma-jasmine-istanbul/issues/13
