### ISSUE TITLE
Q: cache

### ISSUE THREAD

**Issue by asapach** [babel/karma-babel-preprocessor#26]
Is there a way to cache the output of the preprocessor between runs so that it wouldn't have to run transpilation on every file from scratch? With thousands of files this becomes a huge performance issue.

**Comment by jameswlane** [comment]
👍

**Comment by shuhei** [comment]
Sorry for this late reply. This preprocessor only transpiles files one by one. If you want to cache the outputs, it should be a responsibility of Karma itself.
