### ISSUE TITLE
Release 8.0.0?

### ISSUE THREAD

**Issue by mjeanroy** [babel/karma-babel-preprocessor#39]
Hi,

Now that babel released version 7.0.0, it may be the time to officially release version 8.0.0 (already available via the `@next` tag), what do you think?

For information, the `karma-babel-preprocessor@next` tag works fine for me with `@babel/core@7.0.0`.

Thanks for the hard work!

**Comment by stevenvachon** [comment]
Hello?

**Comment by pdesjardins90** [comment]
@shuhei @MattiasBuelens Can either of you merge this [PR](https://github.com/babel/karma-babel-preprocessor/pull/38)? 

Thanks!

**Comment by MattiasBuelens** [comment]
@pdesjardins90 I'm not a maintainer. From what I can see in the commit log, @shuhei and @hzoo have published the previous versions.

I'll ping them in the #development channel on [the Babel Slack](https://slack.babeljs.io/). Although I guess mentioning them in this comment already counts as a ping. 😛

**Comment by hzoo** [comment]
Ok merged https://github.com/babel/karma-babel-preprocessor/pull/38 and published as latest in 8.0.0. Thanks @MattiasBuelens (Sorry, I haven't been watching this repo at all)

**Comment by MattiasBuelens** [comment]
@hzoo Thanks for the quick response! 😄 

Sure, I can help maintain this project a bit. In case you need it for anything, I'm [`mattiasbuelens`](https://www.npmjs.com/~mattiasbuelens) on npm.
