### ISSUE TITLE
Example using karma-babel-preprocessor + karma-browserify + babelify

### ISSUE THREAD

**Issue by benmccann** [babel/karma-babel-preprocessor#49]
The README says:

>babel and karma-babel-preprocessor only convert ES6 modules to CommonJS/AMD/SystemJS/UMD. If you choose CommonJS, you still need to resolve and concatenate CommonJS modules on your own. We recommend karma-browserify + babelify or webpack + babel-loader in such cases.

I was wondering if there's an example of doing either of these anywhere that you could point to? Thanks!

**Comment by shuhei** [comment]
[karma-browserify](https://github.com/Nikku/karma-browserify) and [karma-webpack](https://github.com/webpack-contrib/karma-webpack) have examples in their repositories.
