### ISSUE TITLE
Help with setup

### ISSUE THREAD

**Issue by pbrianmackey** [babel/karma-babel-preprocessor#6]
I installed this tool via npm.  How do I set it up?  The directions skip over a lot of detail.  I edited my karma.conf.js file to include:

```json
    // list of files / patterns to load in the browser
    files: [
      'test-main.js',
      {pattern: 'tests/*.js', included: true}
    ],


    // list of files to exclude
    exclude: [
    ],


    // preprocess matching files before serving them to the browser
    // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
    preprocessors: {
			'src/*.js': ['babel']
    },
		'babelPreprocessor': {
      options: {
        sourceMap: 'inline'
      },
      filename: function(file) {
        return file.originalPath.replace(/\.js$/, '.es5.js');
      },
      sourceFileName: function(file) {
        return file.originalPath;
      }
    },
```

I get error:  `regeneratorRuntime is not defined`.  My files do not update on change.  My original files written in ES6 are located in src/.

**Comment by blesh** [comment]
:+1: ... I could use some guidance here too. It's not very straightforward.

**Comment by pbrianmackey** [comment]
I had success with a slightly different route:  http://stackoverflow.com/questions/28976748/karma-regeneratorruntime-is-not-defined/28988642#28988642

**Comment by shuhei** [comment]
Sorry to be late. I'll update README.
