### ISSUE TITLE
module ids for systemjs including whole user path

### ISSUE THREAD

**Issue by jonricaurte** [babel/karma-babel-preprocessor#9]
Hi,

Below is part of my karma config:

    preprocessors: {
      '**/*.slim': ['slim', 'ng-html2js'],
      '**/*.es6': ['babel']

    },

    babelPreprocessor: {
      options: {
        modules: 'system',
        moduleIds: true
      },
      filename: function(file) {
        return file.originalPath.replace(/\.es6$/, '.js');
      },
      sourceRoot: function(file) {
        return 'app/';
      }
    },

When my code loads, the System.register is not using relative paths of where the file is, but is using the absolute path on the file system. My module ids are System.register("/Users/MyName/Code/myApp/app/assets/javascripts/app/top...")

However, I just want it to be from: System.register("app/top...")

I tried using the babel options (including sourceRoot) but now it shows like:
System.register("app//Users/MyName/Code/myApp/app/assets/javascripts/app/top...")

Thanks.

**Comment by shuhei** [comment]
What if you specify an absolute path for sourceRoot?

**Comment by jonricaurte** [comment]
it adds the following: 

System.register("/app//...")

A workaround I did was this:


      filename: function(file) {
        return file.originalPath.replace(/.*?javascripts\//, '').replace(/\.es6$/, '.js');
      }

**Comment by shuhei** [comment]
I meant an absolute path on the file system instead of on the browser.
